
const GGG5 = {
"ma":	[		"place/site (of/for)",			"n site c",		"place"],
"ki":	[		"tool/appliance (of/for)",		"n c", 			"tool"],
"bo":	[		"body[part] (of/for)",			"n body c", 	"bodypart"],
"boc":	[		"spirit/soul",					"n body", 		"soul"],
"ti":	[		"[f]act (of)",					"n c", 			"act_of"],
"to":	[		"object/thing",					"n c", 			"object"],
"da":	[		"person",						"n c", 			"person"],
"lo":	[		"someone/something",			"n c",			"someone/something"],			
"na":	[		"top",							"n site c", 	"top"],
"nac":	[		"bottom",						"n site", 		"bottom"],
"mi":	[		"I/me",							"n c",			"me"],
"mic":	[		"you",							"n c",			"you"],
"li":	[		"time (of)",					"n time c",		"time"],
"su":	[		"[thought of as one whole] group (of)",	"n c",	"group"],
"suc":	[		"element (of)",					"n c",			"element"],
"nu":	[		"inside",						"n site c",		"inside"],
"nuc":	[		"outside",						"n site",		"outside"],
"se":	[		"oneself",						"n c",			"self"],
"pia":	[		"each other",					"n c",			"each_other"],
"lik":	[		"occurence",					"n c",			"occurence"],
"koi":	[		"solid",						"n ph_str c", 	"solid"],
"lei":	[		"liquid",						"n ph_str c", 	"liquid"],
"fau":	[		"gaseous matter [possibly air]","n ph_str c", 	"gas"],
"nie":	[		"year",							"n time c",		"year"],
"nal":	[		"weekday",						"n time",		"weekday"],
"dia":	[		"day",							"n time c",		"day"],
"hoa":	[		"hour",							"n time",		"hour"],
"leia":	[		"water",						"n c",			"water"],
"tai":	[		"type/way (of)",				"n c",			"type"],
"tia":	[		"side",							"n site c",		"side"],
"tiai":	[		"right side",					"n site c",		"right"],
"tiaic":[		"left side",					"n site",		"left"],
"pae":	[		"parent",						"n c",			"parent"],
"paec":	[		"offspring",					"n",			"offspring"],
"kio":	[		"sibling",						"n c",			"sibling"],
"dio":	[		"story (described by)",			"n c",			"story"],
"nao":	[		"sky",							"n site c",		"sky"],
"naoc":	[		"ground",						"n site",		"ground"],
"mae":	[		"front",						"n site c",		"front"],
"maec":	[		"backside",						"n site",		"backside"],
"nuo":	[		"center",						"n site c",		"center"],
"nuoc":	[		"edge",							"n site",		"edge"],
"heia":	[		"room",							"n site c",		"room"],
"guo":	[		"country/state",				"n site c",		"country"],
"biu":	[		"city/town/village",			"n site c",		"settlement"],
"dom":	[		"building/house (of/for)",		"n site c",		"building"],
"kois":	[		"beast",						"n animal c",	"beast"],
"leis":	[		"fish",							"n animal c",	"fish"],
"faus":	[		"bird",							"n animal c",	"bird"],
"goa":	[		"road",							"n site c",		"road"],
"fiuc":	[		"adult",						"n c",			"adult"],
"fiu":	[		"child",						"n",			"child"],
"sao":	[		"circle/sphere",				"n ph_str c",	"circle"],
"nas":	[		"space",						"n site c",		"space"],
"soi":	[		"word",							"n c",			"word"],
"tcu":	[		"whole",						"n c",			"whole"],
"tcuc":	[		"part (of)",					"n",			"part"],
"den":	[		"electricity",					"n",			"electricity"],
"tui":	[		"bag",							"n c",			"bag"],
"doua":	[		"stone",						"n ph_m c",		"stone"],
"til":	[		"language",						"n c",			"language"],
"ha":	[		"color",						"n c",			"color"],
"lit":	[		"character(of a script)",		"n c",			"character"],
"pap":	[		"paper",						"n",			"paper"],
"fae":	[		"cloth",						"n ph_m c",		"cloth"],
"tcou":	[		"insect",						"n animal c",	"insect"],
"nuk":	[		"container (for)",				"n c",			"container"],
"gul":	[		"flower",						"n plant c",	"flower"],
"mil":	[		"milk",							"n food&cooking c", "milk"],
"mon":	[		"money",						"n c",			"money"],
"boe":	[		"physical matter",				"n ph_str c",	"physical"],
"boec":	[		"non-physical matter",			"n ph_str", 	"non_physical"],
"mur":	[		"wall",							"n c",			"wall"],
"kim":	[		"cream-like substance",			"n food&cooking ph_str","cream"],
"miao":	[		"cat",							"n animal",		"cat"],
"dog":	[		"dog",							"n animal",		"dog"],
"pig":	[		"pig",							"n animal",		"pig"],
"pue":	[		
"oblong binding object homogeneous in the cross section",
												"n ph_str c",	"rope_shaped"],
"bou":	[		"stick-shaped object",			"n ph_str c",	"stick_shaped"],
"hea":	[		"hair",							"n body c",		"hair"],
"tou":	[		"head",							"n body c",		"head"],
"gal":	[		"glass",						"n ph_str c",	"glass"],
"han":	[		"blood",						"n body c",		"blood"],
"hol":	[		"hole(opening)",				"n c",			"hole"],
"bie":	[		"vehicle with a cabin (that travels on)",		"n c",	"vehicle_with_cabin"],
"dok":	[		"document (that certifies)",	"n c",			"document"],
"kom":	[		"personal computer",			"n",			"PC"],
"kut":	[		"angle",						"n",			"angle"],
"tcok":	[		"chocolate",					"n",			"chocolate"],
"pot":	[		"potato",						"n",			"potato"],
"tom":	[		"tomato",						"n",			"tomato"],
"fom":	[		"form/shape",					"n c",			"shape"],
"dot":	[		"dot/point",					"n",			"dot"],
"met":	[		"meter",						"n",			"meter"],
"pant":	[		"trousers",						"n",			"trousers"],
"mes":	[		"meat",							"n c",			"meat"],
"'alk":	[		"alcohol",						"n food&cooking",	"alcohol"],
"ris":	[		"rice",							"n food&cooking",	"rice"],
"'atom":[		"atom",							"n",			"atom"],
"'banan":[		"banana",						"n food&cooking","banana"],
"boa":	[		"board",						"n ph_str c",		"board"],
"tes":	[		"substance",					"n ph_str c",		"substance"],

//transitive verbs

"ne":	[		"cause",					"v tr -sent c",		"cause"],
"fe":	[		"begin",					"v tr -verb c",		"begin"],
"fec":	[		"stop (...ing)",			"v tr -verb",		"stop"],
"go":	[		"go (to)",					"v tr -noun c",		"go"],
"ni":	[		
"experience a feeling/emotion (signalazing about)",	
												"v tr -noun feeling c",	"feel"],
"so":	[		"see/notice (...ing)",				"v tr -sent c",		"notice"],
"pi":	[		"be located (in/at)",				"v tr -noun weak c","be_located"],
"kan":	[		"see/look (at)",					"v tr -sent c",		"see/look"],
"lui":	[		"hear/listen",						"v tr -sent c",		"hear/listen"],
"faui":	[		"perceive smell (of)",				"v tr -noun c",		"smell"],
"gin":	[		"eat/drink",						"v tr -noun food&cooking c",	"eat/drink"],
"ginc":	[		"defecate/urinate",					"v tr -noun",			"defecate/urinate"],
"faue":	[		"breathe",								"v tr -noun c",	"breathe"],
"lie":	[		"be happy (about)",					"v tr -sent repsubj feeling c", "happy"],
"liec":	[		"be sad (about)",					"v tr -sent repsubj feeling",	"sad"],
"tuo":	[		"work (as someone)",				"v tr -verb c",		"work"],
"tua":	[		"try",								"v tr -verb c",		"try"],
"pau":	[		"be prone",							"v tr -verb c",		"prone"],
"pauc":	[		"be prone not",						"v tr -verb",		"prone_not"],
"fei":	[		"find easy",						"v tr -verb c",		"find_easy"],
"feic":	[		"find difficult",					"v tr -verb",		"find_difficult"],
"lu":	[		"be in contact (with)",				"v tr -noun c",		"in_contact"],
"sim":	[		"be similar/same (with)",			"v tr -noun weak c",	"similar"],
"simc":	[		"be different (from)",				"v tr -noun weak",		"different"],
"mit":	[		"meet/see",							"v tr -noun c",		"meet"],
"nom":	[		"be named",							"v tr -noun weak c",	"named"],
"dau":	[		"fight",							"v tr -noun c",		"fight"],
"mo":	[		"be able",							"v tr -verb c",		"able"],
"fi":	[		"enjoy/like (...ing)",				"v tr -sent repsubj feeling c",	"like"],
"fic":	[		"dislike (...ing)",					"v tr -sent repsubj feeling",		"dislike"],
"du":	[		"do/act (...ing)",					"v tr -verb c",					"do"],
"mau":	[		"want",								"v tr -sent repsubj feeling c",	"want"],
"mauc":	[		"diswant",							"v tr -sent repsubj feeling",		"diswant"],
"bi":	[		"and as a result",					"other c",				"and_as_a_result"],
"pao":	[		"be important",						"v intr c",			"important"],
"dis":	[		"say ∕ speak",						"v tr -noun c",		"speak"],
"fo":	[		"be convinced (about)",				"v tr -sent c",		"convinced"],
"he":	[		"ask ∕ suggest ∕ order",			"v tr -sent c",		"ask"],
"nei":	[		"control",							"v tr -noun c",		"control"],
"neic":	[		"obey",								"v tr -noun",		"obey"],
"lua":	[		"do voice",							"v tr -noun c",		"do_voice"],
"seo":	[		"succeed (in)",						"v tr -verb c",		"succeed"],
"hoe":	[		"deserve",							"v tr -sent repsubj c","deserve"],
"pif":	[		"reside (at)",						"v tr -noun c",		"reside"],
"pou":	[		"do thinking (about)",				"v tr -sent c",		"think"],
"kou":	[		"have knowledge (of)",				"v tr -sent c",		"know"],
"hom":	[		"understand",						"v tr -sent c",		"understand"],
"tcek":	[		"test∕check (...ing)",				"v tr -sent c",		"test"],	
"tcie":	[		"cut",								"v tr -noun c",		"cut"],
"diu":	[		"[re]solve",						"v tr -noun c",		"solve"],
"lio":	[		"write",							"v tr -noun c",		"write"],
"lioc":	[		"read",								"v tr -noun",		"read"],
"mai":	[		"be allowed",						"v tr -verb c",		"allowed"],
"maic":	[		"be not allowed",					"v tr -verb",		"forbidden"],
"kem":	[		"commit crime (expressed in)",		"v tr -verb c",		"commit_crime"],
"dea":	[		
"be in a state ∕ condition (described by)",			"v tr -verb c",		"in_state"],
"fan":	[		"have fun (...ing)",				"v tr -verb feeling c","have_fun"],
"fanc":	[		"be bored (with)",					"v tr -verb feeling",	"bored"],
"ten":	[		"hold",								"v tr -noun c",		"hold"],
"bio":	[		"be in danger (from)",				"v tr -noun c",		"in_danger"],
"bioc":	[		"be safe (from)",					"v tr -noun",		"safe"],
"fia":	[		
"be romantically ∕ sexually attracted (to)",		"v tr -noun c",		"in_love"],
"hae":	[		"find funny",						"v tr -noun feeling c","find_funny"],
"nuf":	[		"be concentrated (on)",				"v tr -sent repsubj c","concentrated"],
"heu":	[		"have",								"v tr -noun c",		"have"],
"bai":	[		"buy",								"v tr -noun c",		"buy"],
"baic":	[		"sell",								"v tr -noun c",		"sell"],
"due":	[		"surpass",							"v tr c",				"surpass"],
"hou":	[		"respect",							"v tr -noun feeling c",	"respect"],
"houc":	[		"disdain",							"v tr -noun feeling",	"disdain"],
"kie":	[		"use (...ing)",						"v tr -noun c",			"use"],
"neo":	[		"need",								"v tr -sent repsubj c",	"need"],
"toe":	[		"be tense (because of)",			"v tr -sent repsubj c",	"tense"],
"toec":	[		"be relaxed (at)",					"v tr -sent repsubj",	"relaxed"],
"tceo":	[		"be angry (at)",					"v tr -sent feeling c",	"angry"],
"kuk":	[		"cook",								"v tr -noun food&cooking c","cook"],
"tcus":	[		"choose",							"v tr -sent repsubj c",	"choose"],
"beo":	[		"be",								"v tr c",					"be"],
"sit":	[		"sit (on)",							"v tr -noun c",				"sit"],
"tcoi":	[		"taste",							"v tr -noun food&cooking c","taste"],
"kis":	[		"kiss",								"v tr -noun",				"kiss"],
"dil":	[		"have a deal",						"v tr -sent",				"deal"],
"maie":	[		"do real magic (expressed in)",		"v tr -verb c",			"do_magic"],
//"fai":	[		"find",								"v tr -noun c",		""],
"poe":	[		"get in sexual contact (with)",		"v tr -noun c",			"have_sex"],
"meu":	[		"press/push",						"v tr -noun c",			"push"],
"meuc":	[		"pull",								"v tr -noun",			"pull"],
"goi":	[		"be instead (of)",					"v tr c",				"instead"],
"kao":	[		"be in order(organized)",			"v intr c",				"organized"],
"kaoc":	[		"be in chaos(disorganized)",		"v intr",				"chaotic"],
"mel":	[		"be married (to)",					"v tr -noun",			"married"],
"tok":	[		"flow",								"v c",					"flow"],
"kua":	[		"crawl/climb",						"v tr -noun c",			"crawl"],
"ham":	[		"bite",								"v tr -noun c",			"bite"],
"suoc":	[		"playback",							"v tr -noun",			"playback"],
"suo":	[		"record",							"v tr -noun c",			"record"],
"lis":	[		"wait (for)",						"v tr -sent time c",	"wait"],
"hua":	[		"paint/draw",						"v tr -noun c",			"draw"],
"hit":	[		"hit",								"v tr -noun c",			"hit"],	
"do":	[		"PASSIVE",							"v tr -verb c",			"PASSIVE"],
"has":	[		"undo (...ing)",					"v tr -verb c",			"undo"],
"mus":	[		"play (a musical instrument)",		"v c",					"play"],




//intransitive verbs and adjectives

"mei":	[		"be alive",								"v intr c",		"live"],
"meic":	[		"be dead",								"v intr",		"dead"],
"bei":	[		"exist",								"v intr c",		"exist"],
"beic":	[		"not exist",							"v intr",		"not_exist"],
"nai":	[		"warm/hot",								"adj c",		"warm/hot"],
"naic":	[		"cold",									"adj",			"cold"],
"dai":	[		"large",								"adj ph_str c",	"big"],
"daic":	[		"small",								"adj ph_str",	"small"],
"lon":	[		"long",									"adj ph_str c",	"long"],
"lonc":	[		"short",								"adj ph_str",	"short"],
"hai":	[		"high/tall",							"adj c",		"high"],
"haic":	[		"low",									"adj",			"low"],
"son":	[		"be asleep",							"v intr c",		"sleep"],
"dei":	[		"true",									"adj intr c",	"true"],
"deic":	[		"false",								"adj intr",		"false"],
"la":	[		"good",									"adj c",		"good"],
"lac":	[		"bad",									"adj",			"bad"],
"foi":	[		"fast",									"adj c",		"fast"],
"foic":	[		"slow",									"adj",			"slow"],
"mou":	[		"be in movement",						"v intr c",		"move"],
"faia":	[		"be on fire",							"v intr c",		"on_fire"],
"hie":	[		"be frozen",							"v intr c",		"frozen"],
"dou":	[		"hard(not soft)",						"adj ph_str c",	"hard"],
"douc":	[		"soft",									"adj ph_str",	"soft"],
"lou":	[		"be injured",							"v c",			"injured"],
"kai":	[		"be open",								"v intr c",		"open"],
"kaic":	[		"be closed",							"v intr",		"closed"],
"san":	[		"healthy",								"adj c",		"healthy"],
"sanc":	[		"ill",									"adj",			"ill"],
"fuac":	[		"extraordinary",						"adj c",		"extraordinary"],
"fua":	[		"ordinary",								"adj",			"ordinary"],
"pua":	[		"clean",								"adj c",		"clean"],
"puac":	[		"dirty",								"adj",			"dirty"],
"leiu":	[		"wet",									"adj c",		"wet"],
"leiuc":[		"dry",									"adj",			"dry"],
"tae":	[		"vertical",								"adj c",		"vertical"],
"taec":	[		"horizontal",							"adj",			"horizontal"],
"geo":	[		"be full of energy",					"v intr c",		"have_energy"],
"gan":	[		"strong",								"adj c",		"strong"],
"ganc":	[		"weak",									"adj",			"weak"],
"bam":	[		"explode",								"v intr",		"explode"],
"lai":	[		"light",								"adj c",		"light"],
"laic":	[		"dark",									"adj",			"dark"],
"hei":	[		"back and forth (...ing)",				"v intr c",		"back_and_forth"],
//"som":	[		"early><late",							"adj c",		""],
//"kon":	[		"particular><general",					"adj c",		""],
"tcoe":	[	"straight",									"adj ph_str c",		"straight"],
"tcoec":[	"curved",									"adj ph_str",		"curved"],
"sea":	[	"next",										"adj c",		"next"],
"seac":	[	"previous",									"adj",			"previous"],
"suit":	[	"sweet",									"adj food&cooking",		"sweet"],
"tcua":	[	"sour",										"adj food&cooking",		"sour"],
"sal":	[	"salty",									"adj food&cooking",		"salty"],
"'tcin":[	"Chinese",									"adj",		"Chinese"],
"pol":	[	"Polish",									"adj",		"Polish"],
"'eng":	[	"English",									"adj",		"English"],
"rus":	[	"Russian",									"adj",		"Russian"],
"dan":	[	"Danish",									"adj",		"Danish"],	
"'ame":	[	"related to the people of the US",			"adj",		"USA"],
"turk":	[	"Turkish",									"adj",		"Turkish"],
"'iapon":	[	"Japanese",								"adj",		"Japanese"],
"'asia":	[	"Mongoloid",							"adj",		"Mongoloid"],
"'europ":	[	"European",								"adj",		"European"],




"sil":	[		"slide",				"v intr c",		"slide"],

//prefixes

"pa":	[		"GIANT-",				"prefix c",		"GIANT"],
"pac":	[		"a little",				"prefix",		"LITTLE"],
"no":	[		"not",					"prefix c",		"not"],
"ga":	[		"completely",			"prefix c",		"completely"],
"gau":	[		"regularly",			"prefix c",		"regularly"],
"gauc":	[		"not regularly",		"prefix",		"not_regularly"],
"sol":	[		"only",					"prefix c",		"only"],
"noi":	[		"...,too,",				"prefix c",		"also"],
"les":	[		"even",					"prefix c",		"even"],
"bis":	[		"(emphasis)",			"prefix c",		"EMPHASIS"],
"doi":	[		"...back",				"prefix c",		"back"],
"piu":	[		"more/extra",			"prefix c",		"more"],
"piuc":	[		"less",					"prefix",		"less"],
"ho":	[		"o great respected",	"prefix c",		"o_great"],
"hoc":	[		"ew-",					"prefix",		"ew"],
"tce":	[		"(angry/rude)",			"prefix c",		"ANGRY"],

"bui":	[		"would",				"prefix c",		"would"],
"fa":	[		"FUTURE",				"prefix c",		"FUTURE"],
"fac":	[		"PAST",					"prefix",		"PAST"],
"nau":	[		"NOW",					"prefix c",		"NOW"],
"di":	[		"(informal ∕ slang)",	"prefix c",		"INFORMAL"],
"tul":	[		"too much",				"prefix c",		"too_much"],
"tulc":	[		"too little",			"prefix",		"too_little"],



"ke":	[		"what",					"n c",		"what"],
"ta":	[		"this/that",			"n c",		"that"],
"gao":	[		"all",					"n c",		"all"],
"gaoc":	[		"none",					"n",		"none"],
"te":	[		"male (who is)",		"n c",		"male"],
"tec":	[		"female (who is)",		"n c",		"female"],


// prepositions
"foa":	[		"for the sake of",		"prep c",		"for_the_sake"],
"ko":	[		"[along] with",			"prep c",		"with"],
"tu":	[		"towards",				"prep c",		"to"],
"tuc":	[		"from",					"prep",			"from"],
"sau":	[		"after",				"prep c",		"after"],
"sauc":	[		"before",				"prep",			"before"],
"pio":	[		"in exchange for",		"prep c",		"in_exchange"],
"nue":	[		"among/between",		"prep c",		"among"],
"dol":	[		"alongside",			"prep c",		"alongside"],
"dolc":	[		"against",				"prep",			"against"],

//numbers
"nul":	[		"0",					"other number c",		"zero"],
"mu":	[		"1",					"other number c",		"one"],
"ku":	[		"2",					"other number c",		"two"],
"tei":	[		"3",					"other number c",		"three"],
"fou":	[		"4",					"other number c",		"four"],
"pet":	[		"5",					"other number c",		"five"],
"lok":	[		"6",					"other number c",		"six"],
"set":	[		"7",					"other number c",		"seven"],
"hau":	[		"8",					"other number c",		"eight"],
"nef":	[		"9",					"other number c",		"nine"],
//others
"duo":	[		"and",					"other c",		"and"],
"duoc":	[		"or",					"other",		"or"],
"keo":	[		"but",					"other c",		"but"],
"keoc":	[		"although",				"other",		"although"],
"hoi":	[		"because (of)",			"other c",		"because"],
"hoic":	[		"therefore",			"other",		"therefore"],
"sei":	[		"if",					"other c",		"if"],
"seic":	[		"then",					"other",		"then"],
"tci":	[		"[QUESTION CLAUSE]",	"other c",		"QUESTION"],
"ba":	[		"[SUBJECT]:",			"other c",		"SUBJECT"],
"bac":	[		"[OBJECT]:",			"other",		"OBJECT"],
"hu":	[		"[MAIN VERB]:",			"other c",		"MAIN_VERB"],
"hi":	[		"[ADVERB]:",			"other c",		"ADVERB"],
"gu":	[		"[ADJECTIVE]:",			"other c",		"ADJECTIVE"],
"de":	[		"of",					"other c",		"of"],
"gi":	[		"quantity ∕ extent",	"n c",			"quantity"],
"pe":	[		"[CLAUSE]:",			"other c",		"CLAUSE"],
"lun":	[		"be near (...ing)",		"v tr weak c",	"near"],
"lunc":	[		"be far (from)",		"v tr weak",	"far"]
};

let anti_GGG5 = {};
for (let w in GGG5) {
	let t = GGG5[w];
	if (t) anti_GGG5[t[2]] = w;
}